### ISSUE TITLE
Repository 명칭 변경 okky-sample -> okky-contents

### ISSUE THREAD

**Issue by SunKyungCho** [okjsp/okky-sample#1]
제가 잘못알고 있는게 아니라면
현재 리파짓토리는 okky-contents 로 사용을 하고 있는데요. 

명칭을 변경해줘야 할것 같은데 저한테 그런 권한을 없는것 같네요. 
okky-contents 로 변경 요청드립니다.

**Comment by kwamuki** [comment]
그렇네요, ^^ 명칭 변경 했습니다~
